AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  home-assistant-proxy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 2048

Parameters:
    LogLevel:
        Type: String
        Default: error
        AllowedValues:
        - error
        - warn
        - info
        - debug
    HomeAssistantUrl:
        Type: String
        Default: https://myhost.com
    DebugHomeAssistantLlaToken:
        Type: String
        Default: ''
        NoEcho: True
    IgnoreSslValidation:
        Type: String
        Default: 'false'
        AllowedValues:
        - 'true'
        - 'false'

Resources:
  HomeAssistantProxy:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          HOME_ASSISTANT_URL: !Ref HomeAssistantUrl
          DEBUG_HOME_ASSISTANT_LLA_TOKEN: !Ref DebugHomeAssistantLlaToken
          IGNORE_SSL_VALIDATION: !Ref IgnoreSslValidation

  HomeAssistantProxyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HomeAssistantProxy}"
      RetentionInDays: 1

Outputs:
  HomeAssistantProxy:
    Description: HomeAssistantProxy Lambda Function ARN
    Value: !GetAtt HomeAssistantProxy.Arn
  HomeAssistantProxyIamRole:
    Description: Implicit IAM Role created for HomeAssistantProxy Lambda Function
    Value: !GetAtt HomeAssistantProxyRole.Arn
