AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  home-assistant-proxy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Parameters:
  HomeAssistantUrl:
    Type: String
    Default: https://myhost.com
  DebugLogsEnabled:
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  DebugHomeAssistantLlaToken:
    Type: String
    Default: ''
    NoEcho: True
  TlsValidation:
    Type: Number
    Default: '1'
    AllowedValues:
    - '1'
    - '0'

Resources:
  HomeAssistantProxy:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          HOME_ASSISTANT_URL: !Ref HomeAssistantUrl
          DEBUG_LOGS_ENABLED: !Ref DebugLogsEnabled
          DEBUG_HOME_ASSISTANT_LLA_TOKEN: !Ref DebugHomeAssistantLlaToken
          NODE_TLS_REJECT_UNAUTHORIZED: !Ref TlsValidation

  HomeAssistantProxyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HomeAssistantProxy}"
      RetentionInDays: 1

Outputs:
  HomeAssistantProxy:
    Description: HomeAssistantProxy Lambda Function ARN
    Value: !GetAtt HomeAssistantProxy.Arn
  HomeAssistantProxyIamRole:
    Description: Implicit IAM Role created for HomeAssistantProxy Lambda Function
    Value: !GetAtt HomeAssistantProxyRole.Arn
